import os 
import time
import webbrowser

print('''


    █▀▀ ▀█▀   █▀▄▀█ █▀█ █▀▄ █▀▄ █ █▄ █ █▀▀   █▀▄ █▀█ █ █ █ █▄ █ █   █▀█ ▄▀█ █▀▄ █▀▀ █▀█
    █▄█  █    █ ▀ █ █▄█ █▄▀ █▄▀ █ █ ▀█ █▄█   █▄▀ █▄█ ▀▄▀▄▀ █ ▀█ █▄▄ █▄█ █▀█ █▄▀ ██▄ █▀▄

''')
print("By Leo (@Not--Leo - YT)")
print("Designed For Windows 10/11 Devices...\n")


# shows the options
print("Route 0: Get Monke Mod Manager")
print("Route 1: Link Cable")
print("Route 2: Air Link")
print("Route 3: ALVR\n")

RouteSelect = input("Select Your Route: (0/1/2/3)\n")

# check if it's a valid input
if  RouteSelect == '0' or RouteSelect == '1' or RouteSelect == '2' or RouteSelect == '3' or RouteSelect == '4':

    if RouteSelect == '0':
        webbrowser.open_new("https://github.com/DeadlyKitten/MonkeModManager/releases/download/1.3.1/MonkeModManager.exe")
        os.system('cls')
        print("Downloading MMM Software")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading MMM Software.")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading MMM Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading MMM Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download Should have started in your Web Browser, please select a location for your download.")
        time.sleep(5)
        os.system('cls')
        done = input("If not, please try again (r) otherwise, you may exit (enter)! \n")
        if done == 'r':
            webbrowser.open_new("https://www.oculus.com/download_app/?id=1582076955407037&utm_source=www.google.com")
            exit = input("Retrying... Please check your Web Browser")
        else:
            os.system('cls')
            print("Thanks for using the GT Modding Tool (V1.0.0) By Leo!")
            time.sleep(3)
        
    
    
    if RouteSelect == '1':
        webbrowser.open_new("https://www.oculus.com/download_app/?id=1582076955407037&utm_source=www.google.com")
        os.system('cls')
        print("Downloading Oculus Software")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software.")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download Should have started in your Web Browser, please select a location for your download.")
        time.sleep(5)
        os.system('cls')
        done = input("If not, please try again (r) otherwise, you may exit (enter)! \n")
        if done == 'r':
            webbrowser.open_new("https://www.oculus.com/download_app/?id=1582076955407037&utm_source=www.google.com")
            exit = input("Retrying... Please check your Web Browser")
        else:
            os.system('cls')
            print("Thanks for using the GT Modding Tool (V1.0.0) By Leo!")
            time.sleep(3)
            
    elif RouteSelect == '2':
        webbrowser.open_new("https://www.oculus.com/download_app/?id=1582076955407037&utm_source=www.google.com")
        os.system('cls')
        print("Downloading Oculus Software")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software.")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading Oculus Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download Should have started in your Web Browser, please select a location for your download.")
        time.sleep(5)
        os.system('cls')
        done = input("If not, please try again (r) otherwise, you may exit (enter)!\n")
        if done == 'r':
            webbrowser.open_new("https://www.oculus.com/download_app/?id=1582076955407037&utm_source=www.google.com")
            exit = input("Retrying... Please check your Web Browser")
        else:
            os.system('cls')
            print("Thanks for using the GT Modding Tool (V1.0.0) By Leo!")
            time.sleep(3)
                    
    elif RouteSelect == '3':
    
        #download ALVR PC
        webbrowser.open_new("https://github.com/alvr-org/ALVR/releases/download/v20.4.0/ALVR_Installer_v20.4.0.exe")
        print("Downloading ALVR (V20.4.0) PC Software")
        time.sleep(0.3)
        print("Downloading ALVR (V20.4.0) PC Software.")
        os.system('cls')
        print("Downloading ALVR (V20.4.0) PC Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading ALVR (V20.4.0) PC Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download should have started in your Web Browser, please select a location for your download.")
        time.sleep(6)
        os.system('cls')
        
        #wait for user
        print("The Next Download will start in: 15")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 14")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 13")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 12")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 11")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 10")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 9")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 8")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 7")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 6")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 5")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 4")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 3")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 2")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 1")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 0")
        os.system('cls')
        
        #donload sidequest (2)
        webbrowser.open_new("https://github.com/SideQuestVR/SideQuest/releases/download/v0.10.38/SideQuest-Setup-0.10.38-x64-win.exe")
        print("Downloading SideQuest (V0.10.38) PC Software")
        time.sleep(0.3)
        print("Downloading SideQuest (V0.10.38) PC Software.")
        os.system('cls')
        print("Downloading SideQuest (V0.10.38) PC Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading SideQuest (V0.10.38) PC Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download should have started in your Web Browser, please select a location for your download.")
        time.sleep(6)
        os.system('cls')
        
        #wait for user
        print("The Next Download will start in: 15")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 14")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 13")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 12")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 11")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 10")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 9")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 8")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 7")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 6")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 5")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 4")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 3")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 2")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 1")
        time.sleep(1)
        os.system('cls')
        print("The Next Download will start in: 0")
        os.system('cls')

        #donload ALVR (3)
        webbrowser.open_new("https://github.com/alvr-org/ALVR/releases/download/v20.4.0/alvr_client_android.apk")
        print("Downloading ALVR (V20.4.0) Headset Software")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading ALVR (V20.4.0) Headset Software.")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading ALVR (V20.4.0) Headset Software..")
        time.sleep(0.3)
        os.system('cls')
        print("Downloading ALVR (V20.4.0) Headset Software...")
        time.sleep(0.5)
        os.system('cls')
        print("Your download should have started in your Web Browser and should be in your downloads folder already.")
        time.sleep(5)
        os.system('cls')
        print("Thanks for using the GT Modding Tool (V1.0.0) By Leo!")
        time.sleep(5)
        
    elif RouteSelect == '4':
        print("You found the secret option!")
        webbrowser.open_new("https://www.youtube.com/channel/UC1KfgGi_GDn0LvIPn-3pGXg")
        time.sleep(5)
        
else:
    print("ERROR: Invalid Input (0x001")
    time.sleep(0.5)
    try:
        filenameCWD = str(os.path.basename(__file__))
        os.startfile(f"{filenameCWD}")
    except:
        print(f"ERROR: Unable To Locate '{os.path.basename(__file__)}' (0x002)")
        time.sleep(0.3)
        exit()

        
            
        
    